create table if not exists users ( id INTEGER GENERATED BY DEFAULT AS IDENTITY(START WITH 1, INCREMENT BY 1) PRIMARY KEY, name varchar(255), lastName varchar(255), email varchar(255), password varchar(255) );

--!com id como primary key e auto increment--
--!create table if not exists contacts ( id INTEGER IDENTITY PRIMARY KEY, name varchar(45), email varchar(45), phone varchar(45));--